# This file is machine-generated - editing it directly is not advised

[[AbstractAlgebra]]
deps = ["InteractiveUtils", "LinearAlgebra", "Markdown", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "1269e15291a2be5d77a9a42abeee4e6f4b662ab9"
repo-rev = "master"
repo-url = "AbstractAlgebra.jl"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.5.4"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Logging", "SHA"]
git-tree-sha1 = "c7361ce8a2129f20b0e05a89f7070820cfed6648"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.6"

[[CMake]]
deps = ["BinDeps"]
git-tree-sha1 = "c67a8689dc5444adc5eb2be7d837100340ecba11"
uuid = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
version = "1.1.2"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "84aa74986c5b9b898b0d1acaf3258741ee64754f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "2.1.0"

[[CxxWrap]]
deps = ["BinaryProvider", "Libdl"]
git-tree-sha1 = "c7865f82d1ccfd98d11bba256bd22c27b5ca2864"
uuid = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
version = "0.8.2"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[GAP]]
deps = ["GAPTypes", "Libdl", "Pkg", "REPL"]
git-tree-sha1 = "c8b25f544ab1a53967a84dc0b46fddc537ac960f"
repo-rev = "master"
repo-url = "GAP.jl"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
version = "0.2.1"

[[GAPTypes]]
git-tree-sha1 = "d6269367f194023a1b9bf05b41af2bbbabf0cc77"
uuid = "cd4130c4-8d21-11e9-2a29-61e008680c2d"
version = "1.0.0"

[[Hecke]]
deps = ["AbstractAlgebra", "Distributed", "InteractiveUtils", "Libdl", "LinearAlgebra", "Markdown", "Nemo", "Pkg", "Printf", "Profile", "Random", "Requires", "Serialization", "SparseArrays", "Test"]
git-tree-sha1 = "b3a9860e9da419386f4fd4d70a84b98e463d9184"
repo-rev = "master"
repo-url = "Hecke.jl"
uuid = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
version = "0.6.5"

[[HomalgProject]]
deps = ["GAP"]
git-tree-sha1 = "aa77e619195f392c75b8c07e923bd364cf95f28a"
repo-rev = "master"
repo-url = "HomalgProject.jl"
uuid = "50bd374c-87b5-11e9-015a-2febe71398bd"
version = "0.1.0"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "1f7a25b53ec67f5e9422f1f551ee216503f4a0fa"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.20.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Nemo]]
deps = ["AbstractAlgebra", "BinaryProvider", "InteractiveUtils", "Libdl", "LinearAlgebra", "Markdown", "Random", "Test"]
git-tree-sha1 = "fc4eff1f5599564df3a2b6ecf3daa30565195e4c"
repo-rev = "master"
repo-url = "Nemo.jl"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"
version = "0.14.3"

[[Oscar]]
deps = ["AbstractAlgebra", "Hecke", "Nemo", "Singular"]
git-tree-sha1 = "9c9fca9b3a909e0a747865aa1bb7537bdb0db271"
repo-rev = "master"
repo-url = "Oscar.jl"
uuid = "baad09ba-1e75-5037-8b48-eec3a04d358e"
version = "0.0.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Polymake]]
deps = ["BinaryProvider", "CMake", "CxxWrap", "JSON", "Libdl", "Markdown", "Pkg", "REPL"]
git-tree-sha1 = "f49a6d7257171dbe5095e92201fcf6768ea86ad9"
repo-rev = "master"
repo-url = "Polymake.jl"
uuid = "d720cf60-89b5-51f5-aff5-213f193123e7"
version = "0.2.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Singular]]
deps = ["AbstractAlgebra", "CxxWrap", "Libdl", "LinearAlgebra", "Markdown", "Nemo", "Statistics"]
git-tree-sha1 = "30c4e841fa9248a6c8294fde538f6766c332b6af"
repo-rev = "master"
repo-url = "Singular.jl"
uuid = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
version = "0.0.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
